"""Core algorithm blocks used by the public imaging-sonar ice-draft pipeline.

Only the implementation blocks required by the command-line workflow are kept.
The original research notebook, datasets, manual annotations, and internal
experiment-specific cells are intentionally excluded from this repository.
"""

from __future__ import annotations

CELL_SOURCES = ['',
 '',
 'from pathlib import Path\n'
 'import json\n'
 'import csv\n'
 '\n'
 'import numpy as np\n'
 'import xarray as xr\n'
 'import matplotlib.pyplot as plt\n'
 'from matplotlib.colors import LinearSegmentedColormap\n'
 '\n'
 'from scipy.ndimage import gaussian_filter1d\n'
 'from scipy.signal import find_peaks\n'
 'from skimage.measure import label, regionprops\n'
 '\n'
 'from ice_sonar_pipeline.oculus_backward_mapping import (\n'
 '    SonarGridConfig,\n'
 '    backward_map_ping_center_plane,\n'
 '    fill_internal_holes,\n'
 '    open_oculus_dataset,\n'
 '    read_ping_frame,\n'
 ')\n'
 '\n'
 'PROJECT_DIR = Path.cwd()\n'
 'NC_DIR = Path.cwd()\n'
 'NC_FILE = globals().get("NC_FILE")\n'
 'BATCH_PINGS = list(globals().get("BATCH_PINGS", []))\n'
 'OUTPUT_ROOT = Path(globals().get("OUTPUT_ROOT", Path.cwd() / "output"))\n'
 'OUTPUT_DIR = Path(globals().get("OUTPUT_DIR", OUTPUT_ROOT / "01_gray_preprocessing"))\n'
 'OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n'
 '\n'
 '# Runtime profile. The expensive binary parameter search is run on representative\n'
 '# tuning pings, then the selected global binary config is applied to every ping.\n'
 'BINARY_TUNING_PING_STEP = 50\n'
 'SAVE_GRAY_SELECTED_FIGURES = False\n'
 'SAVE_BINARY_SELECTED_FIGURES = True\n'
 'SAVE_ROLL_CORRECTION_FIGURES = False\n'
 'SAVE_PER_PING_QC_CARDS = False\n'
 '\n'
 'GRID_CONFIG = SonarGridConfig(\n'
 '    range_min_m=0.0,\n'
 '    range_max_m=15.0,\n'
 '    grid_resolution_m=0.05,\n'
 '    azimuth_half_angle_deg=65.0,\n'
 '    vertical_aperture_deg=20.0,\n'
 '    interpolation="linear",\n'
 ')\n'
 '\n'
 'OCULUS_CMAP = LinearSegmentedColormap.from_list(\n'
 '    "oculus_amber",\n'
 '    ["#000000", "#140b00", "#5c3400", "#c98200", "#ffd447", "#fffdf2"],\n'
 '    N=256,\n'
 ')\n'
 'CMAP = OCULUS_CMAP\n'
 'plt.rcParams["font.family"] = "Arial"\n'
 'CLIP_PERCENTILES = (2, 98)\n'
 '\n'
 'print("Project root:", PROJECT_DIR)\n'
 'print("Output root:", OUTPUT_ROOT)\n'
 'print("Gray preprocessing directory:", OUTPUT_DIR)\n'
 'print("Batch pings:", BATCH_PINGS)\n'
 'print("Grid config:", GRID_CONFIG)\n'
 'print("Binary tuning ping step:", BINARY_TUNING_PING_STEP)\n'
 'print("Save gray selected figures:", SAVE_GRAY_SELECTED_FIGURES)\n'
 'print("Save binary selected figures:", SAVE_BINARY_SELECTED_FIGURES)\n'
 'print("Save roll correction figures:", SAVE_ROLL_CORRECTION_FIGURES)\n'
 'print("Save per-ping QC cards:", SAVE_PER_PING_QC_CARDS)\n',
 '',
 'if NC_FILE is None:\n'
 '    nc_files = sorted(NC_DIR.glob("*.nc"), key=lambda p: p.stat().st_mtime)\n'
 '    if not nc_files:\n'
 '        raise FileNotFoundError(f"No .nc file found in {NC_DIR}")\n'
 '    NC_PATH = nc_files[-1]\n'
 'else:\n'
 '    NC_PATH = Path(NC_FILE)\n'
 '\n'
 'ds = open_oculus_dataset(NC_PATH)\n'
 '\n'
 'def choose_image_var(dataset):\n'
 '    if "backscatter" in dataset.data_vars:\n'
 '        return "backscatter"\n'
 '    candidates = [\n'
 '        name for name, da in dataset.data_vars.items()\n'
 '        if np.issubdtype(da.dtype, np.number) and len(da.shape) >= 2 and all(s > 0 for s in '
 'da.shape)\n'
 '    ]\n'
 '    if not candidates:\n'
 '        raise ValueError("No non-empty 2D/3D numeric image variable was found.")\n'
 '    return candidates[0]\n'
 '\n'
 'IMAGE_VAR = choose_image_var(ds)\n'
 'print("NetCDF:", NC_PATH)\n'
 'print("Image variable:", IMAGE_VAR)\n'
 'print(ds)\n',
 '',
 '# Shared preprocessing parameters. They are fixed before candidate selection.\n'
 'BACKGROUND_BIN_M = 0.15\n'
 'ADAPTIVE_THRESHOLD_LOW_PERCENTILE = 25.0\n'
 'ADAPTIVE_THRESHOLD_HIGH_PERCENTILE = 75.0\n'
 'ADAPTIVE_THRESHOLD_IQR_GAIN = 1.0\n'
 'ADAPTIVE_THRESHOLD_SMOOTH_BINS = 10\n'
 'MIN_BIN_PIXEL_COUNT = 10\n'
 '\n'
 '# Artifact geometry model.\n'
 'ICE_MIN_Z_M = 6.0\n'
 'ICE_BAND_HALF_WIDTH_M = 0.55\n'
 'CENTER_HALF_WIDTH_M = 0.22\n'
 'CENTER_SIDE_INNER_M = 0.40\n'
 'CENTER_SIDE_OUTER_M = 1.30\n'
 'CENTER_SIDE_PERCENTILE = 70.0\n'
 'CENTER_EXCESS = 0.12\n'
 'CENTER_SIDE_PRESERVE_LEVEL = 0.55\n'
 'LOBE_Z_MARGIN_M = 1.25\n'
 'LOBE_MAX_WIDTH_M = 6.0\n'
 'COMPONENT_THRESHOLD = 0.25\n'
 'Z_PEAK_MIN_DISTANCE_M = 0.45\n'
 'Z_PEAK_PROMINENCE_FRACTION = 0.06\n'
 'PROJECTION_PIXEL_THRESHOLD = 0.35\n'
 '\n'
 '# Candidate parameter sets. The automatic selector chooses one global set.\n'
 'CANDIDATE_CONFIGS = [\n'
 '    {"name": "conservative", "weak_floor": 0.05, "post_floor": 0.04, "center_min_level": 0.25, '
 '"center_attenuation": 0.35, "lobe_attenuation": 0.45},\n'
 '    {"name": "balanced", "weak_floor": 0.08, "post_floor": 0.06, "center_min_level": 0.25, '
 '"center_attenuation": 0.22, "lobe_attenuation": 0.30},\n'
 '    {"name": "strong_mvp", "weak_floor": 0.11, "post_floor": 0.08, "center_min_level": 0.28, '
 '"center_attenuation": 0.15, "lobe_attenuation": 0.22},\n'
 '    {"name": "center_focused", "weak_floor": 0.08, "post_floor": 0.06, "center_min_level": 0.22, '
 '"center_attenuation": 0.12, "lobe_attenuation": 0.38},\n'
 '    {"name": "ice_preserving", "weak_floor": 0.07, "post_floor": 0.05, "center_min_level": 0.30, '
 '"center_attenuation": 0.20, "lobe_attenuation": 0.35},\n'
 '    {"name": "lobe_focused", "weak_floor": 0.10, "post_floor": 0.07, "center_min_level": 0.28, '
 '"center_attenuation": 0.20, "lobe_attenuation": 0.15},\n'
 '    {"name": "high_threshold", "weak_floor": 0.13, "post_floor": 0.10, "center_min_level": 0.32, '
 '"center_attenuation": 0.18, "lobe_attenuation": 0.20},\n'
 ']\n'
 '\n'
 'def percentile_normalize(data, percentiles=(2, 98)):\n'
 '    finite = np.isfinite(data)\n'
 '    if not np.any(finite):\n'
 '        return np.full_like(data, np.nan, dtype=float), np.nan, np.nan\n'
 '    vmin, vmax = np.nanpercentile(data[finite], percentiles)\n'
 '    if not np.isfinite(vmin) or not np.isfinite(vmax) or vmax <= vmin:\n'
 '        vmax = vmin + 1.0\n'
 '    normalized = (data - vmin) / (vmax - vmin)\n'
 '    normalized = np.clip(normalized, 0.0, 1.0)\n'
 '    normalized[~finite] = np.nan\n'
 '    return normalized, float(vmin), float(vmax)\n'
 '\n'
 'def fill_and_smooth_curve(x, curve, smooth_bins, fallback_value=0.0):\n'
 '    good = np.isfinite(curve)\n'
 '    if np.count_nonzero(good) >= 2:\n'
 '        filled = np.interp(x, x[good], curve[good], left=curve[good][0], right=curve[good][-1])\n'
 '    elif np.count_nonzero(good) == 1:\n'
 '        filled = np.full_like(curve, curve[good][0], dtype=float)\n'
 '    else:\n'
 '        filled = np.full_like(curve, fallback_value, dtype=float)\n'
 '    smooth_bins = max(1, int(smooth_bins))\n'
 '    if smooth_bins % 2 == 0:\n'
 '        smooth_bins += 1\n'
 '    kernel = np.ones(smooth_bins, dtype=float) / smooth_bins\n'
 '    return np.convolve(filled, kernel, mode="same"), smooth_bins\n'
 '\n'
 'def normalized_profile(values):\n'
 '    values = np.asarray(values, dtype=float)\n'
 '    vmax = np.nanmax(values) if np.any(np.isfinite(values)) else np.nan\n'
 '    if not np.isfinite(vmax) or vmax <= 0:\n'
 '        return np.zeros_like(values, dtype=float)\n'
 '    return values / vmax\n'
 '\n'
 'def compute_z_projection(image, z_axis, dz_m):\n'
 '    finite = np.isfinite(image)\n'
 '    projection_sum = np.nansum(image, axis=1)\n'
 '    projection_count = np.sum(finite & (image >= PROJECTION_PIXEL_THRESHOLD), '
 'axis=1).astype(float)\n'
 '    projection_score = 0.65 * normalized_profile(projection_sum) + 0.35 * '
 'normalized_profile(projection_count)\n'
 '    smooth_sigma = max(1.0, Z_PEAK_MIN_DISTANCE_M / abs(dz_m) / 3.0)\n'
 '    projection_smooth = gaussian_filter1d(np.nan_to_num(projection_score, nan=0.0), '
 'sigma=smooth_sigma)\n'
 '    return projection_score, projection_smooth\n'
 '\n'
 'def find_z_peaks(projection_smooth, z_axis, dz_m):\n'
 '    finite_max = float(np.nanmax(projection_smooth)) if np.any(np.isfinite(projection_smooth)) '
 'else 0.0\n'
 '    prominence = max(1e-6, Z_PEAK_PROMINENCE_FRACTION * finite_max)\n'
 '    distance = max(1, int(round(Z_PEAK_MIN_DISTANCE_M / abs(dz_m))))\n'
 '    peaks, props = find_peaks(projection_smooth, prominence=prominence, distance=distance)\n'
 '    rows = []\n'
 '    for i, row in enumerate(peaks):\n'
 '        rows.append({\n'
 '            "row": int(row),\n'
 '            "z_m": float(z_axis[row]),\n'
 '            "score": float(projection_smooth[row]),\n'
 '            "prominence": float(props["prominences"][i]),\n'
 '        })\n'
 '    rows = sorted(rows, key=lambda item: item["prominence"], reverse=True)\n'
 '    high_peaks = [item for item in rows if item["z_m"] >= ICE_MIN_Z_M]\n'
 '    if high_peaks:\n'
 '        selected = max(high_peaks[:5], key=lambda item: item["z_m"] + 2.0 * item["prominence"])\n'
 '    elif rows:\n'
 '        selected = rows[0]\n'
 '    else:\n'
 '        row = int(np.nanargmax(projection_smooth))\n'
 '        selected = {"row": row, "z_m": float(z_axis[row]), "score": '
 'float(projection_smooth[row]), "prominence": 0.0}\n'
 '    return rows, selected\n'
 '\n'
 'def map_ping(dataset, ping_idx, image_var, grid_config):\n'
 '    image, metadata = read_ping_frame(dataset, ping_idx, image_var=image_var)\n'
 '    mapped = backward_map_ping_center_plane(image, metadata, grid_config)\n'
 '    filled = fill_internal_holes(\n'
 '        image=mapped["mapped_backscatter"],\n'
 '        valid_mask=mapped["valid_mask"],\n'
 '        y_axis_m=mapped["y_axis_m"],\n'
 '        z_axis_m=mapped["z_axis_m"],\n'
 '        max_fill_distance_m=globals().get("ALGORITHM_PARAMETERS", {}).get("grid", {}).get("hole_fill_max_distance_m", 0.15),\n'
 '    )\n'
 '    return {\n'
 '        "metadata": metadata,\n'
 '        "linear": filled["linear"],\n'
 '        "valid_mask": mapped["valid_mask"],\n'
 '        "y_axis": mapped["y_axis_m"],\n'
 '        "z_axis": mapped["z_axis_m"],\n'
 '    }\n'
 '\n'
 'def adaptive_range_threshold(linear_image, valid_mask, y_axis, z_axis):\n'
 '    base = np.asarray(linear_image, dtype=float).copy()\n'
 '    base[~valid_mask] = np.nan\n'
 '    y_grid, z_grid = np.meshgrid(y_axis, z_axis)\n'
 '    range_grid = np.hypot(y_grid, z_grid)\n'
 '    finite_base = valid_mask & np.isfinite(base)\n'
 '    range_max = float(np.nanmax(range_grid[valid_mask]))\n'
 '    range_edges = np.arange(0.0, range_max + BACKGROUND_BIN_M, BACKGROUND_BIN_M)\n'
 '    if range_edges.size < 2:\n'
 '        raise ValueError("Not enough range bins for adaptive threshold.")\n'
 '    range_centers = 0.5 * (range_edges[:-1] + range_edges[1:])\n'
 '    threshold_curve = np.full(range_centers.shape, np.nan, dtype=float)\n'
 '\n'
 '    for bin_index, (r0, r1) in enumerate(zip(range_edges[:-1], range_edges[1:])):\n'
 '        bin_mask = finite_base & (range_grid >= r0) & (range_grid < r1)\n'
 '        values = base[bin_mask]\n'
 '        if values.size >= MIN_BIN_PIXEL_COUNT:\n'
 '            p_low = np.nanpercentile(values, ADAPTIVE_THRESHOLD_LOW_PERCENTILE)\n'
 '            p_high = np.nanpercentile(values, ADAPTIVE_THRESHOLD_HIGH_PERCENTILE)\n'
 '            threshold_curve[bin_index] = p_low + ADAPTIVE_THRESHOLD_IQR_GAIN * (p_high - p_low)\n'
 '\n'
 '    threshold_curve, smooth_bins = fill_and_smooth_curve(\n'
 '        range_centers,\n'
 '        threshold_curve,\n'
 '        ADAPTIVE_THRESHOLD_SMOOTH_BINS,\n'
 '    )\n'
 '    threshold_grid = np.interp(range_grid, range_centers, threshold_curve, '
 'left=threshold_curve[0], right=threshold_curve[-1])\n'
 '    adaptive = base.copy()\n'
 '    adaptive[base < threshold_grid] = np.nan\n'
 '    adaptive[~valid_mask] = np.nan\n'
 '    adaptive_norm, vmin, vmax = percentile_normalize(adaptive, CLIP_PERCENTILES)\n'
 '    adaptive_norm[~valid_mask] = np.nan\n'
 '    return adaptive_norm, {\n'
 '        "range_centers": range_centers,\n'
 '        "threshold_curve": threshold_curve,\n'
 '        "smooth_bins": smooth_bins,\n'
 '        "norm_vmin": vmin,\n'
 '        "norm_vmax": vmax,\n'
 '    }\n'
 '\n'
 'def safe_energy(image, mask):\n'
 '    values = image[mask & np.isfinite(image)]\n'
 '    return float(np.nansum(values)) if values.size else 0.0\n'
 '\n'
 'def build_context(adaptive_image, valid_mask, y_axis, z_axis):\n'
 '    y_grid, z_grid = np.meshgrid(y_axis, z_axis)\n'
 '    dy = float(np.nanmean(np.diff(y_axis)))\n'
 '    dz = float(np.nanmean(np.diff(z_axis)))\n'
 '    projection_score, projection_smooth = compute_z_projection(adaptive_image, z_axis, dz)\n'
 '    peaks, ice_peak = find_z_peaks(projection_smooth, z_axis, dz)\n'
 '    ice_z = float(ice_peak["z_m"])\n'
 '    masks = {\n'
 '        "center_core": np.abs(y_grid) <= CENTER_HALF_WIDTH_M,\n'
 '        "center_nonice": (np.abs(y_grid) <= CENTER_HALF_WIDTH_M) & (z_grid < ice_z - '
 'ICE_BAND_HALF_WIDTH_M),\n'
 '        "lower_lobe_region": (z_grid < ice_z - LOBE_Z_MARGIN_M) & (np.abs(y_grid) <= 7.5),\n'
 '        "ice_band": valid_mask & (np.abs(z_grid - ice_z) <= ICE_BAND_HALF_WIDTH_M),\n'
 '        "weak_annular": valid_mask & np.isfinite(adaptive_image) & (adaptive_image < 0.18),\n'
 '    }\n'
 '    baseline = {\n'
 '        "ice_energy": safe_energy(adaptive_image, masks["ice_band"]),\n'
 '        "center_energy": safe_energy(adaptive_image, masks["center_nonice"]),\n'
 '        "lower_energy": safe_energy(adaptive_image, masks["lower_lobe_region"]),\n'
 '        "weak_pixels": int(np.count_nonzero(masks["weak_annular"])),\n'
 '        "finite_pixels": int(np.count_nonzero(np.isfinite(adaptive_image) & valid_mask)),\n'
 '    }\n'
 '    return {\n'
 '        "y_grid": y_grid,\n'
 '        "z_grid": z_grid,\n'
 '        "dy": dy,\n'
 '        "dz": dz,\n'
 '        "peaks": peaks,\n'
 '        "initial_ice_peak": ice_peak,\n'
 '        "initial_ice_z": ice_z,\n'
 '        "masks": masks,\n'
 '        "baseline": baseline,\n'
 '        "initial_projection_score": projection_score,\n'
 '        "initial_projection_smooth": projection_smooth,\n'
 '    }\n'
 '\n'
 'def suppress_artifacts(adaptive_image, valid_mask, y_axis, z_axis, context, config):\n'
 '    cleaned = np.asarray(adaptive_image, dtype=float).copy()\n'
 '    cleaned[~valid_mask] = np.nan\n'
 '    dy = context["dy"]\n'
 '    dz = context["dz"]\n'
 '    ice_z = context["initial_ice_z"]\n'
 '    center_core_mask = context["masks"]["center_core"]\n'
 '\n'
 '    weak_mask = valid_mask & np.isfinite(cleaned) & (cleaned < config["weak_floor"])\n'
 '    cleaned[weak_mask] = np.nan\n'
 '\n'
 '    side_cols = (np.abs(y_axis) >= CENTER_SIDE_INNER_M) & (np.abs(y_axis) <= '
 'CENTER_SIDE_OUTER_M)\n'
 '    side_values = cleaned[:, side_cols]\n'
 '    side_support = np.full(cleaned.shape[0], np.nan, dtype=float)\n'
 '    for row in range(cleaned.shape[0]):\n'
 '        row_values = side_values[row, :]\n'
 '        finite_row = np.isfinite(row_values)\n'
 '        if np.count_nonzero(finite_row) >= 3:\n'
 '            side_support[row] = np.nanpercentile(row_values[finite_row], '
 'CENTER_SIDE_PERCENTILE)\n'
 '\n'
 '    support_finite = np.isfinite(side_support)\n'
 '    if np.count_nonzero(support_finite) >= 2:\n'
 '        side_support = np.interp(z_axis, z_axis[support_finite], side_support[support_finite], '
 'left=0.0, right=0.0)\n'
 '    else:\n'
 '        side_support = np.zeros_like(z_axis, dtype=float)\n'
 '\n'
 '    center_threshold = np.maximum(side_support + CENTER_EXCESS, config["center_min_level"])\n'
 '    center_artifact_mask = (\n'
 '        center_core_mask\n'
 '        & np.isfinite(cleaned)\n'
 '        & (cleaned > center_threshold[:, None])\n'
 '        & (side_support[:, None] < CENTER_SIDE_PRESERVE_LEVEL)\n'
 '    )\n'
 '    cleaned[center_artifact_mask] = cleaned[center_artifact_mask] * '
 'config["center_attenuation"]\n'
 '\n'
 '    binary = np.isfinite(cleaned) & (cleaned >= COMPONENT_THRESHOLD)\n'
 '    component_labels = label(binary, connectivity=2)\n'
 '    lobe_mask = np.zeros_like(binary, dtype=bool)\n'
 '    for region in regionprops(component_labels, intensity_image=np.nan_to_num(cleaned, '
 'nan=0.0)):\n'
 '        rows = region.coords[:, 0]\n'
 '        cols = region.coords[:, 1]\n'
 '        z_max = float(z_axis[int(rows.max())])\n'
 '        z_centroid = float(z_axis[int(round(region.centroid[0]))])\n'
 '        y_width = float(y_axis[int(cols.max())] - y_axis[int(cols.min())]) if cols.size else '
 '0.0\n'
 '        area_m2 = float(region.area * abs(dy) * abs(dz))\n'
 '        below_ice = z_max < ice_z - 0.45 or z_centroid < ice_z - LOBE_Z_MARGIN_M\n'
 '        compact_or_low = (y_width <= LOBE_MAX_WIDTH_M) or (area_m2 < 0.80)\n'
 '        if below_ice and compact_or_low:\n'
 '            lobe_mask[rows, cols] = True\n'
 '    cleaned[lobe_mask] = cleaned[lobe_mask] * config["lobe_attenuation"]\n'
 '\n'
 '    cleaned[np.isfinite(cleaned) & (cleaned < config["post_floor"])] = np.nan\n'
 '    cleaned[~valid_mask] = np.nan\n'
 '    cleaned = np.clip(cleaned, 0.0, 1.0)\n'
 '\n'
 '    suppress_mask = np.full(cleaned.shape, np.nan, dtype=float)\n'
 '    suppress_mask[weak_mask] = 1.0\n'
 '    suppress_mask[center_artifact_mask] = 2.0\n'
 '    suppress_mask[lobe_mask] = 3.0\n'
 '    return cleaned, {\n'
 '        "weak_mask": weak_mask,\n'
 '        "center_mask": center_artifact_mask,\n'
 '        "lobe_mask": lobe_mask,\n'
 '        "suppress_mask": suppress_mask,\n'
 '    }\n'
 '\n'
 'def prepare_noise_suppression(linear_image, valid_mask, y_axis, z_axis):\n'
 '    adaptive_image, adaptive_meta = adaptive_range_threshold(linear_image, valid_mask, y_axis, '
 'z_axis)\n'
 '    context = build_context(adaptive_image, valid_mask, y_axis, z_axis)\n'
 '    adaptive_removed_mask = (\n'
 '        valid_mask\n'
 '        & np.isfinite(linear_image)\n'
 '        & ~np.isfinite(adaptive_image)\n'
 '    )\n'
 '    return {\n'
 '        "linear_input": linear_image,\n'
 '        "adaptive_image": adaptive_image,\n'
 '        "adaptive_meta": adaptive_meta,\n'
 '        "adaptive_removed_mask": adaptive_removed_mask,\n'
 '        "context": context,\n'
 '    }\n'
 '\n'
 'def run_noise_suppression(prepared, valid_mask, y_axis, z_axis, config):\n'
 '    cleaned, masks = suppress_artifacts(\n'
 '        prepared["adaptive_image"],\n'
 '        valid_mask,\n'
 '        y_axis,\n'
 '        z_axis,\n'
 '        prepared["context"],\n'
 '        config,\n'
 '    )\n'
 '    combined_mask = np.array(masks["suppress_mask"], copy=True)\n'
 '    range_or_weak_mask = prepared["adaptive_removed_mask"] | masks["weak_mask"]\n'
 '    combined_mask[range_or_weak_mask] = 1.0\n'
 '    combined_mask[masks["center_mask"]] = 2.0\n'
 '    combined_mask[masks["lobe_mask"]] = 3.0\n'
 '    masks = {\n'
 '        **masks,\n'
 '        "range_threshold_mask": prepared["adaptive_removed_mask"],\n'
 '        "range_or_weak_mask": range_or_weak_mask,\n'
 '        "suppress_mask": combined_mask,\n'
 '    }\n'
 '    return {\n'
 '        "linear_input": prepared["linear_input"],\n'
 '        "adaptive_image": prepared["adaptive_image"],\n'
 '        "adaptive_meta": prepared["adaptive_meta"],\n'
 '        "context": prepared["context"],\n'
 '        "cleaned": cleaned,\n'
 '        "masks": masks,\n'
 '    }\n'
 '\n'
 'def projection_quality(cleaned, context, z_axis):\n'
 '    projection_score, projection_smooth = compute_z_projection(cleaned, z_axis, context["dz"])\n'
 '    peaks, selected = find_z_peaks(projection_smooth, z_axis, context["dz"])\n'
 '    selected_score = float(selected["score"])\n'
 '    selected_prominence = float(selected.get("prominence", 0.0) or 0.0)\n'
 '    competitors = [p["score"] for p in peaks if abs(p["z_m"] - selected["z_m"]) > 0.5]\n'
 '    competitor_score = float(max(competitors)) if competitors else 0.0\n'
 '    peak_contrast = max(0.0, selected_score - competitor_score)\n'
 '    z_shift = abs(float(selected["z_m"]) - float(context["initial_ice_z"]))\n'
 '    quality = selected_score + 0.7 * selected_prominence + 0.4 * peak_contrast - 0.12 * z_shift\n'
 '    return {\n'
 '        "projection_score": projection_score,\n'
 '        "projection_smooth": projection_smooth,\n'
 '        "peaks": peaks,\n'
 '        "selected_peak": selected,\n'
 '        "peak_quality": float(quality),\n'
 '        "peak_score": selected_score,\n'
 '        "peak_prominence": selected_prominence,\n'
 '        "peak_contrast": float(peak_contrast),\n'
 '        "peak_z_shift_m": float(z_shift),\n'
 '    }\n'
 '\n'
 'def score_result(cleaned, adaptive_image, context, z_axis):\n'
 '    baseline = context["baseline"]\n'
 '    masks = context["masks"]\n'
 '    ice_ratio = safe_energy(cleaned, masks["ice_band"]) / baseline["ice_energy"] if '
 'baseline["ice_energy"] else np.nan\n'
 '    center_ratio = safe_energy(cleaned, masks["center_nonice"]) / baseline["center_energy"] if '
 'baseline["center_energy"] else 0.0\n'
 '    lower_ratio = safe_energy(cleaned, masks["lower_lobe_region"]) / baseline["lower_energy"] if '
 'baseline["lower_energy"] else 0.0\n'
 '    finite_ratio = int(np.count_nonzero(np.isfinite(cleaned) & np.isfinite(adaptive_image))) / '
 'baseline["finite_pixels"] if baseline["finite_pixels"] else np.nan\n'
 '    weak_remaining = int(np.count_nonzero(np.isfinite(cleaned) & masks["weak_annular"])) / '
 'baseline["weak_pixels"] if baseline["weak_pixels"] else 0.0\n'
 '    pq = projection_quality(cleaned, context, z_axis)\n'
 '\n'
 '    score = (\n'
 '        0.55 * ice_ratio\n'
 '        + 0.25 * pq["peak_quality"]\n'
 '        + 0.15 * pq["peak_contrast"]\n'
 '        - 0.28 * center_ratio\n'
 '        - 0.22 * lower_ratio\n'
 '        - 0.10 * weak_remaining\n'
 '        - 0.04 * abs(finite_ratio - 0.55)\n'
 '    )\n'
 '    if ice_ratio < 0.85:\n'
 '        score -= 0.55 * (0.85 - ice_ratio)\n'
 '    if pq["peak_z_shift_m"] > 1.0:\n'
 '        score -= 0.20 * (pq["peak_z_shift_m"] - 1.0)\n'
 '\n'
 '    return {\n'
 '        "score": float(score),\n'
 '        "ice_retention": float(ice_ratio),\n'
 '        "center_residual": float(center_ratio),\n'
 '        "lobe_residual": float(lower_ratio),\n'
 '        "finite_ratio": float(finite_ratio),\n'
 '        "weak_annular_remaining": float(weak_remaining),\n'
 '        "peak_quality": float(pq["peak_quality"]),\n'
 '        "peak_score": float(pq["peak_score"]),\n'
 '        "peak_prominence": float(pq["peak_prominence"]),\n'
 '        "peak_contrast": float(pq["peak_contrast"]),\n'
 '        "peak_z_shift_m": float(pq["peak_z_shift_m"]),\n'
 '        "selected_ice_z_m": float(pq["selected_peak"]["z_m"]),\n'
 '        "selected_peak": pq["selected_peak"],\n'
 '        "peaks": pq["peaks"],\n'
 '        "projection_score": pq["projection_score"],\n'
 '        "projection_smooth": pq["projection_smooth"],\n'
 '    }\n'
 '\n'
 'def write_csv(path, rows, fieldnames):\n'
 '    path.parent.mkdir(parents=True, exist_ok=True)\n'
 '    with path.open("w", newline="", encoding="utf-8-sig") as f:\n'
 '        writer = csv.DictWriter(f, fieldnames=fieldnames)\n'
 '        writer.writeheader()\n'
 '        for row in rows:\n'
 '            writer.writerow({key: row.get(key, "") for key in fieldnames})\n'
 '\n'
 'def render_final_figure(ping_idx, linear_input, cleaned, masks, metrics, config, y_axis, z_axis, '
 'output_path):\n'
 '    extent = [float(y_axis[0]), float(y_axis[-1]), float(z_axis[0]), float(z_axis[-1])]\n'
 '    mvp_cmap = CMAP.copy()\n'
 '    mvp_cmap.set_bad("#000000")\n'
 '    linear_display, _, _ = percentile_normalize(linear_input, CLIP_PERCENTILES)\n'
 '\n'
 '    fig, axes = plt.subplots(2, 2, figsize=(13.0, 8.2), dpi=150, constrained_layout=True)\n'
 '    axes[0, 0].imshow(linear_display, extent=extent, origin="lower", aspect="equal", '
 'cmap=mvp_cmap, vmin=0.0, vmax=1.0)\n'
 '    axes[0, 0].set_title("Linear-interpolated input", fontname="Arial")\n'
 '    im1 = axes[0, 1].imshow(cleaned, extent=extent, origin="lower", aspect="equal", '
 'cmap=mvp_cmap, vmin=0.0, vmax=1.0)\n'
 '    axes[0, 1].set_title(f"Noise-suppressed output | global {config[\'name\']}", '
 'fontname="Arial")\n'
 '    im2 = axes[1, 0].imshow(masks["suppress_mask"], extent=extent, origin="lower", '
 'aspect="equal", cmap="viridis", vmin=1.0, vmax=3.0)\n'
 '    axes[1, 0].set_title("Suppression masks: 1 range/weak, 2 center, 3 lobe", fontname="Arial")\n'
 '\n'
 '    axp = axes[1, 1]\n'
 '    axp.plot(metrics["projection_score"], z_axis, color="#9aa0a6", linewidth=1.0, '
 'label="projection score")\n'
 '    axp.plot(metrics["projection_smooth"], z_axis, color="#c98200", linewidth=1.6, '
 'label="smoothed")\n'
 '    for peak in metrics["peaks"][:6]:\n'
 '        axp.scatter(peak["score"], peak["z_m"], s=20, color="#c44e52")\n'
 '        axp.text(peak["score"], peak["z_m"], f" {peak[\'z_m\']:.2f} m", fontsize=7, '
 'va="center")\n'
 '    axp.axhline(metrics["selected_ice_z_m"], color="#4c72b0", linewidth=1.2, linestyle="--", '
 'label="selected candidate")\n'
 '    axp.set_title("z_s projection / peak detection", fontname="Arial")\n'
 '    axp.set_xlabel("Normalized projection score", fontname="Arial")\n'
 '    axp.set_ylabel("z_s center-beam forward (m)", fontname="Arial")\n'
 '    axp.grid(True, alpha=0.25, linestyle=":")\n'
 '    axp.legend(loc="lower right", fontsize=7, frameon=True)\n'
 '\n'
 '    for ax in axes.ravel()[:3]:\n'
 '        ax.set_xlabel("y_s port / cross-track (m)", fontname="Arial")\n'
 '        ax.set_ylabel("z_s center-beam forward (m)", fontname="Arial")\n'
 '        ax.grid(True, alpha=0.25, linestyle=":")\n'
 '\n'
 '    fig.colorbar(im1, ax=axes[0, 1], fraction=0.046, pad=0.04, label="Normalized intensity")\n'
 '    fig.colorbar(im2, ax=axes[1, 0], fraction=0.046, pad=0.04, ticks=[1, 2, 3], '
 'label="Suppression class")\n'
 '    fig.suptitle(\n'
 '        f"Unified sonar noise suppression | ping {ping_idx} | ice '
 'z={metrics[\'selected_ice_z_m\']:.2f} m | score={metrics[\'score\']:.3f}",\n'
 '        y=1.02,\n'
 '        fontname="Arial",\n'
 '    )\n'
 '    fig.savefig(output_path, dpi=180, bbox_inches="tight")\n'
 '    plt.close(fig)\n',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'from datetime import datetime\n'
 'from matplotlib.path import Path as MplPath\n'
 'from matplotlib.patches import Polygon as MplPolygon\n'
 'from matplotlib.widgets import PolygonSelector\n'
 '\n'
 'MANUAL_MASK_DIR = OUTPUT_ROOT / "02_manual_masks"\n'
 'MANUAL_MASK_DIR.mkdir(parents=True, exist_ok=True)\n'
 'MANUAL_MASK_JSON = MANUAL_MASK_DIR / "user_remove_masks.json"\n'
 'MANUAL_MASK_SUMMARY_CSV = MANUAL_MASK_DIR / "manual_noise_mask_summary.csv"\n'
 'MANUAL_MASK_OPERATOR = "operator"\n'
 'MANUAL_MASK_DELETE_VALUE = np.nan\n'
 '\n'
 '\n'
 'def manual_now_string():\n'
 '    return datetime.now().isoformat(timespec="seconds")\n'
 '\n'
 '\n'
 'def new_manual_mask_store():\n'
 '    return {\n'
 '        "version": 1,\n'
 '        "created_by": "imaging_sonar_ice_draft_pipeline",\n'
 '        "coordinate_system": {\n'
 '            "x": "y_s port / cross-track",\n'
 '            "y": "z_s center-beam forward",\n'
 '            "units": "m",\n'
 '            "origin": "backward-mapped sonar center-plane grid",\n'
 '        },\n'
 '        "edit_policy": "remove-only QC mask before binary segmentation; does not draw or create '
 'ice-bottom curve",\n'
 '        "pings": {},\n'
 '    }\n'
 '\n'
 '\n'
 'def load_manual_mask_store(mask_json=MANUAL_MASK_JSON):\n'
 '    mask_json = Path(mask_json)\n'
 '    if not mask_json.exists():\n'
 '        return new_manual_mask_store()\n'
 '    store = json.loads(mask_json.read_text(encoding="utf-8"))\n'
 '    store.setdefault("version", 1)\n'
 '    store.setdefault("coordinate_system", new_manual_mask_store()["coordinate_system"])\n'
 '    store.setdefault("edit_policy", new_manual_mask_store()["edit_policy"])\n'
 '    store.setdefault("pings", {})\n'
 '    return store\n'
 '\n'
 '\n'
 'def save_manual_mask_store(store, mask_json=MANUAL_MASK_JSON):\n'
 '    mask_json = Path(mask_json)\n'
 '    mask_json.parent.mkdir(parents=True, exist_ok=True)\n'
 '    mask_json.write_text(json.dumps(store, ensure_ascii=False, indent=2), encoding="utf-8")\n'
 '    return mask_json\n'
 '\n'
 '\n'
 'def polygon_area_m2(points):\n'
 '    pts = np.asarray(points, dtype=float)\n'
 '    if pts.ndim != 2 or pts.shape[0] < 3:\n'
 '        return 0.0\n'
 '    y = pts[:, 0]\n'
 '    z = pts[:, 1]\n'
 '    return float(0.5 * abs(np.dot(y, np.roll(z, -1)) - np.dot(z, np.roll(y, -1))))\n'
 '\n'
 '\n'
 'def polygon_to_mask(points, y_axis, z_axis):\n'
 '    pts = np.asarray(points, dtype=float)\n'
 '    if pts.ndim != 2 or pts.shape[0] < 3:\n'
 '        return np.zeros((len(z_axis), len(y_axis)), dtype=bool)\n'
 '    y_grid, z_grid = np.meshgrid(y_axis, z_axis)\n'
 '    path = MplPath(pts)\n'
 '    flat_points = np.column_stack([y_grid.ravel(), z_grid.ravel()])\n'
 '    return path.contains_points(flat_points).reshape(y_grid.shape)\n'
 '\n'
 '\n'
 'def get_ping_remove_polygons(store, ping_idx):\n'
 '    ping_entry = store.get("pings", {}).get(str(int(ping_idx)), {})\n'
 '    polygons = []\n'
 '    for item in ping_entry.get("remove_polygons", []):\n'
 '        if isinstance(item, dict):\n'
 '            polygons.append(item.get("points", []))\n'
 '        else:\n'
 '            polygons.append(item)\n'
 '    return polygons\n'
 '\n'
 '\n'
 'def apply_remove_polygons_to_image(image, y_axis, z_axis, polygons, '
 'delete_value=MANUAL_MASK_DELETE_VALUE):\n'
 '    corrected = np.asarray(image, dtype=float).copy()\n'
 '    combined_mask = np.zeros(corrected.shape, dtype=bool)\n'
 '    for points in polygons:\n'
 '        combined_mask |= polygon_to_mask(points, y_axis, z_axis)\n'
 '    finite_removed = combined_mask & np.isfinite(corrected)\n'
 '    removed_energy = float(np.nansum(corrected[finite_removed])) if np.any(finite_removed) else '
 '0.0\n'
 '    total_energy = float(np.nansum(corrected[np.isfinite(corrected)])) if '
 'np.any(np.isfinite(corrected)) else 0.0\n'
 '    corrected[combined_mask] = delete_value\n'
 '    dy = float(np.nanmean(np.diff(y_axis))) if len(y_axis) > 1 else np.nan\n'
 '    dz = float(np.nanmean(np.diff(z_axis))) if len(z_axis) > 1 else np.nan\n'
 '    pixel_area = abs(dy * dz) if np.isfinite(dy) and np.isfinite(dz) else np.nan\n'
 '    return corrected, combined_mask, {\n'
 '        "manual_remove_polygon_count": int(len(polygons)),\n'
 '        "manual_removed_pixel_count": int(np.count_nonzero(finite_removed)),\n'
 '        "manual_removed_area_m2": float(np.count_nonzero(finite_removed) * pixel_area) if '
 'np.isfinite(pixel_area) else np.nan,\n'
 '        "manual_removed_energy": removed_energy,\n'
 '        "manual_removed_energy_fraction": removed_energy / total_energy if total_energy > 0 else '
 '0.0,\n'
 '    }\n'
 '\n'
 '\n'
 'def apply_manual_masks_to_record(record, store):\n'
 '    ping_idx = int(record["ping"])\n'
 '    frame = record["frame"]\n'
 '    auto_cleaned = np.asarray(record.get("gray_cleaned_auto", record.get("gray_cleaned")), '
 'dtype=float)\n'
 '    polygons = get_ping_remove_polygons(store, ping_idx)\n'
 '    corrected, combined_mask, meta = apply_remove_polygons_to_image(\n'
 '        auto_cleaned,\n'
 '        frame["y_axis"],\n'
 '        frame["z_axis"],\n'
 '        polygons,\n'
 '    )\n'
 '    meta.update({\n'
 '        "ping": ping_idx,\n'
 '        "manual_edited": int(meta["manual_remove_polygon_count"] > 0),\n'
 '        "manual_mask_json": str(MANUAL_MASK_JSON),\n'
 '    })\n'
 '    record["gray_cleaned"] = corrected\n'
 '    record["manual_remove_mask"] = combined_mask\n'
 '    record["manual_mask_meta"] = meta\n'
 '    return meta\n'
 '\n'
 '\n'
 'def apply_manual_masks_to_batch(records, mask_json=MANUAL_MASK_JSON):\n'
 '    store = load_manual_mask_store(mask_json)\n'
 '    rows = []\n'
 '    for record in records:\n'
 '        if "gray_cleaned_auto" not in record:\n'
 '            gray_match = next(item for item in record["candidate_results"] if '
 'item["config"]["name"] == selected_config["name"])\n'
 '            record["gray_cleaned_auto"] = np.asarray(gray_match["cleaned"], dtype=float).copy()\n'
 '        rows.append(apply_manual_masks_to_record(record, store))\n'
 '    return rows\n'
 '\n'
 '\n'
 'def summarize_manual_mask_store(mask_json=MANUAL_MASK_JSON):\n'
 '    store = load_manual_mask_store(mask_json)\n'
 '    rows = []\n'
 '    for ping_key, entry in sorted(store.get("pings", {}).items(), key=lambda kv: int(kv[0])):\n'
 '        polygons = entry.get("remove_polygons", [])\n'
 '        rows.append({\n'
 '            "ping": int(ping_key),\n'
 '            "remove_polygon_count": len(polygons),\n'
 '            "polygon_area_m2": float(sum(polygon_area_m2(poly.get("points", poly)) for poly in '
 'polygons)),\n'
 '            "last_updated": entry.get("last_updated", ""),\n'
 '        })\n'
 '    return rows\n'
 '\n'
 '\n'
 'class ManualNoiseMaskReviewer:\n'
 '    """Interactive remove-mask reviewer for the gray image before binary segmentation."""\n'
 '\n'
 '    def __init__(self, records, mask_json=MANUAL_MASK_JSON, start_ping=None):\n'
 '        self.records = sorted(records, key=lambda item: int(item["ping"]))\n'
 '        self.mask_json = Path(mask_json)\n'
 '        self.store = load_manual_mask_store(self.mask_json)\n'
 '        self.index = 0\n'
 '        if start_ping is not None:\n'
 '            pings = [int(record["ping"]) for record in self.records]\n'
 '            self.index = int(np.argmin(np.abs(np.asarray(pings) - int(start_ping))))\n'
 '        self.pending_polygons = []\n'
 '        self.fig = None\n'
 '        self.axes = None\n'
 '        self.selector = None\n'
 '        self.output = None\n'
 '        self.status = None\n'
 '        self.jump_box = None\n'
 '\n'
 '    def current_record(self):\n'
 '        return self.records[self.index]\n'
 '\n'
 '    def current_ping(self):\n'
 '        return int(self.current_record()["ping"])\n'
 '\n'
 '    def current_polygons(self, include_pending=True):\n'
 '        polygons = get_ping_remove_polygons(self.store, self.current_ping())\n'
 '        if include_pending:\n'
 '            polygons = polygons + self.pending_polygons\n'
 '        return polygons\n'
 '\n'
 '    def _make_selector(self, ax):\n'
 '        try:\n'
 '            return PolygonSelector(\n'
 '                ax,\n'
 '                self._on_polygon_selected,\n'
 '                useblit=True,\n'
 '                props={"color": "#ff4d4d", "linewidth": 1.3, "alpha": 0.95},\n'
 '                handle_props={"markerfacecolor": "#ff4d4d", "markersize": 5},\n'
 '            )\n'
 '        except TypeError:\n'
 '            return PolygonSelector(\n'
 '                ax,\n'
 '                self._on_polygon_selected,\n'
 '                useblit=True,\n'
 '                lineprops={"color": "#ff4d4d", "linewidth": 1.3, "alpha": 0.95},\n'
 '                markerprops={"markerfacecolor": "#ff4d4d", "markersize": 5},\n'
 '            )\n'
 '\n'
 '    def _draw_polygons(self, ax, polygons, color, label, linestyle="-"):\n'
 '        for i, points in enumerate(polygons):\n'
 '            pts = np.asarray(points, dtype=float)\n'
 '            if pts.ndim != 2 or pts.shape[0] < 3:\n'
 '                continue\n'
 '            patch = MplPolygon(\n'
 '                pts,\n'
 '                closed=True,\n'
 '                fill=False,\n'
 '                edgecolor=color,\n'
 '                linewidth=1.4,\n'
 '                linestyle=linestyle,\n'
 '                label=label if i == 0 else None,\n'
 '            )\n'
 '            ax.add_patch(patch)\n'
 '\n'
 '    def _status_text(self):\n'
 '        ping = self.current_ping()\n'
 '        saved = len(get_ping_remove_polygons(self.store, ping))\n'
 '        pending = len(self.pending_polygons)\n'
 '        return f"ping {ping} ({self.index + 1}/{len(self.records)}) | saved remove masks={saved} '
 '| pending={pending}"\n'
 '\n'
 '    def _is_interactive_backend(self):\n'
 '        backend = str(plt.get_backend()).lower()\n'
 '        return ("ipympl" in backend) or ("widget" in backend) or ("nbagg" in backend)\n'
 '\n'
 '    def _require_interactive_backend(self):\n'
 '        if not self._is_interactive_backend():\n'
 '            backend = plt.get_backend()\n'
 '            raise RuntimeError(\n'
 '                "Manual polygon drawing needs an interactive matplotlib backend. "\n'
 '                f"Current backend is {backend!r}. Run the reviewer start cell again; "\n'
 '                "it should switch to `%matplotlib widget`. If it still fails, restart "\n'
 '                "the kernel and run from the top after installing ipympl."\n'
 '            )\n'
 '\n'
 '    def _render(self):\n'
 '        from IPython.display import clear_output, display\n'
 '\n'
 '        record = self.current_record()\n'
 '        frame = record["frame"]\n'
 '        y_axis = frame["y_axis"]\n'
 '        z_axis = frame["z_axis"]\n'
 '        auto_image = np.asarray(record.get("gray_cleaned_auto", record.get("gray_cleaned")), '
 'dtype=float)\n'
 '        saved_polygons = get_ping_remove_polygons(self.store, self.current_ping())\n'
 '        all_polygons = self.current_polygons(include_pending=True)\n'
 '        corrected, combined_mask, meta = apply_remove_polygons_to_image(auto_image, y_axis, '
 'z_axis, all_polygons)\n'
 '        extent = [float(y_axis[0]), float(y_axis[-1]), float(z_axis[0]), float(z_axis[-1])]\n'
 '        review_cmap = CMAP.copy()\n'
 '        review_cmap.set_bad("#000000")\n'
 '\n'
 '        self._require_interactive_backend()\n'
 '        with self.output:\n'
 '            clear_output(wait=True)\n'
 '            if self.fig is not None:\n'
 '                plt.close(self.fig)\n'
 '            self.fig, self.axes = plt.subplots(1, 2, figsize=(13.0, 4.8), dpi=135, '
 'constrained_layout=True)\n'
 '            ax0, ax1 = self.axes\n'
 '            ax0.imshow(auto_image, extent=extent, origin="lower", aspect="equal", '
 'cmap=review_cmap, vmin=0.0, vmax=1.0)\n'
 '            self._draw_polygons(ax0, saved_polygons, "#ff4d4d", "saved remove")\n'
 '            self._draw_polygons(ax0, self.pending_polygons, "#ffd447", "pending remove", '
 'linestyle="--")\n'
 '            ax0.set_title("Auto-denoised input | draw remove mask here", fontname="Arial")\n'
 '\n'
 '            ax1.imshow(corrected, extent=extent, origin="lower", aspect="equal", '
 'cmap=review_cmap, vmin=0.0, vmax=1.0)\n'
 '            if np.any(combined_mask):\n'
 '                overlay = np.ma.masked_where(~combined_mask, combined_mask.astype(float))\n'
 '                ax1.imshow(overlay, extent=extent, origin="lower", aspect="equal", cmap="Reds", '
 'alpha=0.35, vmin=0, vmax=1)\n'
 '            ax1.set_title("Preview sent to binary segmentation", fontname="Arial")\n'
 '\n'
 '            for ax in self.axes:\n'
 '                ax.set_xlabel("y_s port / cross-track (m)", fontname="Arial")\n'
 '                ax.set_ylabel("z_s center-beam forward (m)", fontname="Arial")\n'
 '                ax.grid(True, alpha=0.25, linestyle=":")\n'
 '            if saved_polygons or self.pending_polygons:\n'
 '                ax0.legend(loc="lower right", fontsize=7, frameon=True)\n'
 '            self.fig.suptitle(self._status_text() + " | click vertices on left panel; '
 'double-click or Enter to finish", y=1.03, fontname="Arial")\n'
 '            self.selector = self._make_selector(ax0)\n'
 '            self.fig.canvas.mpl_connect("key_press_event", self._on_key)\n'
 '            display(self.fig.canvas)\n'
 '        if self.status is not None:\n'
 '            self.status.value = self._status_text()\n'
 '\n'
 '    def _on_polygon_selected(self, verts):\n'
 '        if verts is None or len(verts) < 3:\n'
 '            return\n'
 '        polygon = [[float(y), float(z)] for y, z in verts]\n'
 '        self.pending_polygons.append(polygon)\n'
 '        self._render()\n'
 '\n'
 '    def _save_pending(self):\n'
 '        if not self.pending_polygons:\n'
 '            if self.status is not None:\n'
 '                self.status.value = self._status_text() + " | no pending polygon to save"\n'
 '            return\n'
 '        ping_key = str(self.current_ping())\n'
 '        entry = self.store.setdefault("pings", {}).setdefault(ping_key, {})\n'
 '        entry.setdefault("remove_polygons", [])\n'
 '        for points in self.pending_polygons:\n'
 '            entry["remove_polygons"].append({\n'
 '                "points": points,\n'
 '                "created_at": manual_now_string(),\n'
 '                "operator": MANUAL_MASK_OPERATOR,\n'
 '                "reason": "remove clear non-ice echo before binary segmentation",\n'
 '                "area_m2": polygon_area_m2(points),\n'
 '            })\n'
 '        entry["last_updated"] = manual_now_string()\n'
 '        entry["edit_type"] = "remove_only"\n'
 '        save_manual_mask_store(self.store, self.mask_json)\n'
 '        self.pending_polygons = []\n'
 '        apply_manual_masks_to_record(self.current_record(), self.store)\n'
 '        self._render()\n'
 '\n'
 '    def _clear_pending(self):\n'
 '        self.pending_polygons = []\n'
 '        self._render()\n'
 '\n'
 '    def _clear_saved_current(self):\n'
 '        ping_key = str(self.current_ping())\n'
 '        if ping_key in self.store.get("pings", {}):\n'
 '            del self.store["pings"][ping_key]\n'
 '            save_manual_mask_store(self.store, self.mask_json)\n'
 '        self.pending_polygons = []\n'
 '        apply_manual_masks_to_record(self.current_record(), self.store)\n'
 '        self._render()\n'
 '\n'
 '    def _move(self, delta):\n'
 '        self.index = int(np.clip(self.index + delta, 0, len(self.records) - 1))\n'
 '        self.pending_polygons = []\n'
 '        self._render()\n'
 '\n'
 '    def _jump_to_ping(self):\n'
 '        if self.jump_box is None:\n'
 '            return\n'
 '        target = int(self.jump_box.value)\n'
 '        pings = np.asarray([int(record["ping"]) for record in self.records])\n'
 '        self.index = int(np.argmin(np.abs(pings - target)))\n'
 '        self.pending_polygons = []\n'
 '        self._render()\n'
 '\n'
 '    def _on_key(self, event):\n'
 '        if event.key in ["a", "left"]:\n'
 '            self._move(-1)\n'
 '        elif event.key in ["d", "right"]:\n'
 '            self._move(1)\n'
 '        elif event.key == "s":\n'
 '            self._save_pending()\n'
 '        elif event.key == "z":\n'
 '            self._clear_pending()\n'
 '\n'
 '    def show(self):\n'
 '        try:\n'
 '            import ipywidgets as widgets\n'
 '            from IPython.display import display\n'
 '        except Exception as exc:\n'
 '            raise ImportError(\n'
 '                "ManualNoiseMaskReviewer needs ipywidgets in Jupyter. Install it with: "\n'
 '                "conda install -c conda-forge ipywidgets ipympl"\n'
 '            ) from exc\n'
 '        self._require_interactive_backend()\n'
 '\n'
 '        prev_button = widgets.Button(description="Prev", icon="arrow-left", '
 'layout=widgets.Layout(width="90px"))\n'
 '        next_button = widgets.Button(description="Next", icon="arrow-right", '
 'layout=widgets.Layout(width="90px"))\n'
 '        save_button = widgets.Button(description="Save", icon="save", button_style="success", '
 'layout=widgets.Layout(width="90px"))\n'
 '        save_next_button = widgets.Button(description="Save + Next", icon="step-forward", '
 'button_style="success", layout=widgets.Layout(width="125px"))\n'
 '        clear_pending_button = widgets.Button(description="Clear pending", icon="undo", '
 'layout=widgets.Layout(width="125px"))\n'
 '        clear_saved_button = widgets.Button(description="Clear saved", icon="trash", '
 'button_style="warning", layout=widgets.Layout(width="115px"))\n'
 '        jump_button = widgets.Button(description="Jump", icon="search", '
 'layout=widgets.Layout(width="80px"))\n'
 '        self.jump_box = widgets.IntText(value=self.current_ping(), description="ping", '
 'layout=widgets.Layout(width="145px"))\n'
 '        self.status = widgets.HTML(\n'
 '            value=self._status_text()\n'
 '            + " | left-click vertices on the left image; double-click or Enter to finish '
 'polygon"\n'
 '        )\n'
 '        self.output = widgets.Output()\n'
 '\n'
 '        prev_button.on_click(lambda _: self._move(-1))\n'
 '        next_button.on_click(lambda _: self._move(1))\n'
 '        save_button.on_click(lambda _: self._save_pending())\n'
 '        save_next_button.on_click(lambda _: (self._save_pending(), self._move(1)))\n'
 '        clear_pending_button.on_click(lambda _: self._clear_pending())\n'
 '        clear_saved_button.on_click(lambda _: self._clear_saved_current())\n'
 '        jump_button.on_click(lambda _: self._jump_to_ping())\n'
 '\n'
 '        controls = widgets.HBox([\n'
 '            prev_button,\n'
 '            next_button,\n'
 '            save_button,\n'
 '            save_next_button,\n'
 '            clear_pending_button,\n'
 '            clear_saved_button,\n'
 '            self.jump_box,\n'
 '            jump_button,\n'
 '        ])\n'
 '        display(widgets.VBox([controls, self.status, self.output]))\n'
 '        self._render()\n'
 '\n'
 'print("Manual noise-mask tools ready.")\n'
 'print("Mask JSON:", MANUAL_MASK_JSON)\n'
 'print("Use ManualNoiseMaskReviewer(batch_records).show() when interactive QC is needed.")\n',
 '',
 '',
 '',
 '',
 '',
 '',
 'from skimage.measure import label, regionprops\n'
 'from skimage.morphology import binary_closing, binary_opening, remove_small_holes, '
 'remove_small_objects\n'
 'from scipy.ndimage import gaussian_filter1d\n'
 '\n'
 'BINARY_OUTPUT_DIR = OUTPUT_ROOT / "03_binary_masks"\n'
 'BINARY_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n'
 '\n'
 '# Binary segmentation search space. Thresholds are adaptive percentiles per ping.\n'
 '# The code generates candidate configs within physically reasonable bounds and\n'
 '# then chooses one global parameter set by multi-ping scoring.\n'
 'BINARY_SEARCH_SPACE = {\n'
 '    "high_q": [82.0, 86.0, 88.0],\n'
 '    "low_q": [58.0, 62.0, 66.0],\n'
 '    "window_down_m": [0.95, 1.15, 1.35],\n'
 '    "window_up_m": [0.55, 0.70],\n'
 '    "closing_y_m": [0.25, 0.45, 0.65],\n'
 '    "closing_z_m": [0.08, 0.12, 0.16],\n'
 '}\n'
 'BINARY_FIXED_CONFIG = {\n'
 '    "min_area_m2": 0.030,\n'
 '    "min_y_span_m": 0.65,\n'
 '    "opening_y_m": 0.05,\n'
 '    "opening_z_m": 0.05,\n'
 '    "hole_area_m2": 0.030,\n'
 '}\n'
 '\n'
 '# Gap-aware curve and left-side support settings. The left rescue is not a global\n'
 '# threshold relaxation: it is triggered only when the left ice-window has enough\n'
 '# gray-stage energy but the binary mask under-captures that energy.\n'
 'MAX_CURVE_GAP_M = 0.45\n'
 'MAX_CURVE_INTERPOLATE_GAP_M = 0.75\n'
 'LEFT_SUPPORT_Y_MAX_M = -1.0\n'
 'LEFT_SUPPORT_TARGET_SPAN_M = 3.0\n'
 'LEFT_SUPPORT_MIN_SIGNAL_FRACTION = 0.08\n'
 'LEFT_RESCUE_MIN_SUPPORT_SCORE = 0.55\n'
 'LEFT_RESCUE_MAX_DOWN_M = 1.15\n'
 'LEFT_RESCUE_RIDGE_HALF_WIDTH_M = 0.35\n'
 'LEFT_RESCUE_MIN_Y_SPAN_M = 0.45\n'
 'LEFT_RESCUE_CAPTURE_TRIGGER = 0.65\n'
 'LEFT_EDGE_EXTENSION_MIN_GAP_M = 0.75\n'
 'LEFT_EDGE_SUPPORT_GAP_SCALE_M = 2.0\n'
 'LEFT_GRAY_SUPPORT_PERCENTILE = 82.0\n'
 '\n'
 '\n'
 'def generate_binary_candidate_configs(search_space, fixed_config):\n'
 '    configs = []\n'
 '    index = 0\n'
 '    for high_q in search_space["high_q"]:\n'
 '        for low_q in search_space["low_q"]:\n'
 '            if low_q >= high_q:\n'
 '                continue\n'
 '            for window_down_m in search_space["window_down_m"]:\n'
 '                for window_up_m in search_space["window_up_m"]:\n'
 '                    for closing_y_m in search_space["closing_y_m"]:\n'
 '                        for closing_z_m in search_space["closing_z_m"]:\n'
 '                            config = {\n'
 '                                "name": f"binary_cfg_{index:03d}",\n'
 '                                "high_q": high_q,\n'
 '                                "low_q": low_q,\n'
 '                                "window_down_m": window_down_m,\n'
 '                                "window_up_m": window_up_m,\n'
 '                                "closing_y_m": closing_y_m,\n'
 '                                "closing_z_m": closing_z_m,\n'
 '                                **fixed_config,\n'
 '                            }\n'
 '                            configs.append(config)\n'
 '                            index += 1\n'
 '    return configs\n'
 '\n'
 '\n'
 'BINARY_CANDIDATE_CONFIGS = generate_binary_candidate_configs(BINARY_SEARCH_SPACE, '
 'BINARY_FIXED_CONFIG)\n'
 '\n'
 '\n'
 'def make_binary_tuning_pings(batch_pings, step):\n'
 '    batch_pings = [int(ping) for ping in batch_pings]\n'
 '    if not batch_pings:\n'
 '        return []\n'
 '    if step is None or int(step) <= 0:\n'
 '        return batch_pings\n'
 '    first_ping = batch_pings[0]\n'
 '    selected = [\n'
 '        ping for ping in batch_pings\n'
 '        if ((ping - first_ping) % int(step) == 0) or (ping == batch_pings[-1])\n'
 '    ]\n'
 '    if first_ping not in selected:\n'
 '        selected.insert(0, first_ping)\n'
 '    if batch_pings[-1] not in selected:\n'
 '        selected.append(batch_pings[-1])\n'
 '    return sorted(set(selected))\n'
 '\n'
 '\n'
 'BINARY_TUNING_PINGS = make_binary_tuning_pings(BATCH_PINGS, BINARY_TUNING_PING_STEP)\n'
 'BINARY_TUNING_PING_SET = set(BINARY_TUNING_PINGS)\n'
 'print(f"Generated binary candidate configs: {len(BINARY_CANDIDATE_CONFIGS)}")\n'
 'print(f"Binary tuning pings: {BINARY_TUNING_PINGS}")\n'
 'print(\n'
 '    f"Binary search workload: {len(BINARY_TUNING_PINGS)} tuning pings x "\n'
 '    f"{len(BINARY_CANDIDATE_CONFIGS)} configs, then {len(BATCH_PINGS)} selected-config pings."\n'
 ')\n'
 '\n'
 '\n'
 'def meters_to_pixels(length_m, resolution_m, minimum=1):\n'
 '    if length_m <= 0:\n'
 '        return 0\n'
 '    return max(minimum, int(round(float(length_m) / abs(float(resolution_m)))))\n'
 '\n'
 '\n'
 'def binary_component_hysteresis(seed_mask, weak_mask):\n'
 '    labels = label(weak_mask, connectivity=2)\n'
 '    keep_labels = np.unique(labels[seed_mask & (labels > 0)])\n'
 '    if keep_labels.size == 0:\n'
 '        return np.zeros_like(weak_mask, dtype=bool)\n'
 '    return np.isin(labels, keep_labels)\n'
 '\n'
 '\n'
 'def binary_extract_curve(binary_mask, intensity_image, y_axis, z_axis):\n'
 '    curve_z = np.full(y_axis.shape, np.nan, dtype=float)\n'
 '    curve_weight = np.zeros(y_axis.shape, dtype=float)\n'
 '    for col in range(binary_mask.shape[1]):\n'
 '        rows = np.flatnonzero(binary_mask[:, col] & np.isfinite(intensity_image[:, col]))\n'
 '        if rows.size == 0:\n'
 '            continue\n'
 '        weights = np.asarray(intensity_image[rows, col], dtype=float)\n'
 '        if not np.any(weights > 0):\n'
 '            weights = np.ones_like(weights)\n'
 '        curve_z[col] = float(np.average(z_axis[rows], weights=weights))\n'
 '        curve_weight[col] = float(np.nansum(weights))\n'
 '    return curve_z, curve_weight\n'
 '\n'
 '\n'
 'def binary_max_gap_m(active_cols, y_axis):\n'
 '    if active_cols.size <= 1:\n'
 '        return float("inf") if active_cols.size == 0 else 0.0\n'
 '    active_y = y_axis[active_cols]\n'
 '    return float(np.nanmax(np.diff(active_y)))\n'
 '\n'
 '\n'
 'def binary_curve_segments(curve_z, y_axis, max_gap_m=MAX_CURVE_GAP_M, min_points=1):\n'
 '    active_cols = np.flatnonzero(np.isfinite(curve_z))\n'
 '    if active_cols.size == 0:\n'
 '        return []\n'
 '    active_y = np.asarray(y_axis, dtype=float)[active_cols]\n'
 '    breaks = np.flatnonzero(np.diff(active_y) > max_gap_m) + 1\n'
 '    segments = np.split(active_cols, breaks)\n'
 '    return [seg for seg in segments if seg.size >= min_points]\n'
 '\n'
 '\n'
 'def binary_smooth_curve(curve_z, y_axis=None, sigma_cols=3.0, max_gap_m=MAX_CURVE_GAP_M):\n'
 '    curve_z = np.asarray(curve_z, dtype=float)\n'
 '    if y_axis is None:\n'
 '        y_axis = np.arange(curve_z.size, dtype=float)\n'
 '    out = np.full_like(curve_z, np.nan, dtype=float)\n'
 '    for seg in binary_curve_segments(curve_z, y_axis, max_gap_m=max_gap_m, min_points=1):\n'
 '        values = curve_z[seg]\n'
 '        if seg.size >= 3:\n'
 '            local_sigma = min(float(sigma_cols), max(1.0, seg.size / 3.0))\n'
 '            out[seg] = gaussian_filter1d(values, sigma=local_sigma)\n'
 '        else:\n'
 '            out[seg] = values\n'
 '    return out\n'
 '\n'
 '\n'
 'def binary_interpolate_short_gaps(curve_z, y_axis, max_gap_m=MAX_CURVE_INTERPOLATE_GAP_M):\n'
 '    """Linearly connect only short missing spans between measured curve points."""\n'
 '    curve_z = np.asarray(curve_z, dtype=float)\n'
 '    y_axis = np.asarray(y_axis, dtype=float)\n'
 '    out = np.array(curve_z, copy=True)\n'
 '    interpolated = np.zeros(curve_z.shape, dtype=bool)\n'
 '    active_cols = np.flatnonzero(np.isfinite(curve_z))\n'
 '    if active_cols.size <= 1:\n'
 '        return out, interpolated\n'
 '\n'
 '    for left_col, right_col in zip(active_cols[:-1], active_cols[1:]):\n'
 '        if right_col <= left_col + 1:\n'
 '            continue\n'
 '        gap_m = float(abs(y_axis[right_col] - y_axis[left_col]))\n'
 '        if gap_m > max_gap_m:\n'
 '            continue\n'
 '        fill_cols = np.arange(left_col + 1, right_col, dtype=int)\n'
 '        out[fill_cols] = np.interp(\n'
 '            y_axis[fill_cols],\n'
 '            [y_axis[left_col], y_axis[right_col]],\n'
 '            [curve_z[left_col], curve_z[right_col]],\n'
 '        )\n'
 '        interpolated[fill_cols] = True\n'
 '    return out, interpolated\n'
 '\n'
 '\n'
 'def binary_curve_weight_with_interpolation(curve_weight, curve_z, interpolated_mask):\n'
 '    """Give interpolated short-gap points conservative weights for draft statistics."""\n'
 '    curve_weight = np.asarray(curve_weight, dtype=float)\n'
 '    curve_z = np.asarray(curve_z, dtype=float)\n'
 '    out = np.array(curve_weight, copy=True)\n'
 '    active_cols = np.flatnonzero(np.isfinite(curve_z))\n'
 '    for col in np.flatnonzero(interpolated_mask):\n'
 '        left_candidates = active_cols[active_cols < col]\n'
 '        right_candidates = active_cols[active_cols > col]\n'
 '        if left_candidates.size == 0 or right_candidates.size == 0:\n'
 '            out[col] = 0.0\n'
 '            continue\n'
 '        left_col = int(left_candidates[-1])\n'
 '        right_col = int(right_candidates[0])\n'
 '        endpoint_weight = min(float(curve_weight[left_col]), float(curve_weight[right_col]))\n'
 '        out[col] = max(0.0, 0.5 * endpoint_weight)\n'
 '    return out\n'
 '\n'
 '\n'
 'def plot_indexed_segments(ax, x_values, z_values, curve_z, y_axis, *, max_gap_m=MAX_CURVE_GAP_M, '
 'label=None, **plot_kwargs):\n'
 '    x_values = np.asarray(x_values, dtype=float)\n'
 '    z_values = np.asarray(z_values, dtype=float)\n'
 '    first = True\n'
 '    for seg in binary_curve_segments(curve_z, y_axis, max_gap_m=max_gap_m, min_points=1):\n'
 '        finite = np.isfinite(x_values[seg]) & np.isfinite(z_values[seg])\n'
 '        if np.count_nonzero(finite) == 0:\n'
 '            continue\n'
 '        ax.plot(\n'
 '            x_values[seg][finite],\n'
 '            z_values[seg][finite],\n'
 '            label=label if first else None,\n'
 '            **plot_kwargs,\n'
 '        )\n'
 '        first = False\n'
 '\n'
 '\n'
 'def binary_left_support_metrics(binary_mask, cleaned, y_axis, z_axis, ice_z_m):\n'
 '    y_grid, z_grid = np.meshgrid(y_axis, z_axis)\n'
 '    finite_clean = np.isfinite(cleaned)\n'
 '    ice_window = finite_clean & (z_grid >= ice_z_m - 0.85) & (z_grid <= ice_z_m + 0.55)\n'
 '    left_window = ice_window & (y_grid <= LEFT_SUPPORT_Y_MAX_M)\n'
 '\n'
 '    ice_energy_total = safe_energy(cleaned, ice_window)\n'
 '    left_energy_total = safe_energy(cleaned, left_window)\n'
 '    left_signal_fraction = left_energy_total / ice_energy_total if ice_energy_total else 0.0\n'
 '    left_support_needed = left_signal_fraction >= LEFT_SUPPORT_MIN_SIGNAL_FRACTION\n'
 '    left_energy_in_mask = safe_energy(cleaned, binary_mask & left_window)\n'
 '    left_capture = left_energy_in_mask / left_energy_total if left_energy_total else 0.0\n'
 '\n'
 '    gray_cols = np.array([], dtype=int)\n'
 '    left_values = cleaned[left_window]\n'
 '    if left_values.size >= 20 and np.any(np.isfinite(left_values)):\n'
 '        gray_threshold = float(np.nanpercentile(left_values, LEFT_GRAY_SUPPORT_PERCENTILE))\n'
 '        candidate_cols = np.flatnonzero(np.any(left_window, axis=0))\n'
 '        keep_cols = []\n'
 '        for col in candidate_cols:\n'
 '            rows = np.flatnonzero(left_window[:, col] & np.isfinite(cleaned[:, col]))\n'
 '            if rows.size == 0:\n'
 '                continue\n'
 '            vals = cleaned[rows, col]\n'
 '            peak_idx = int(np.nanargmax(vals))\n'
 '            peak_row = rows[peak_idx]\n'
 '            if vals[peak_idx] >= gray_threshold and (ice_z_m - 0.85 <= z_axis[peak_row] <= '
 'ice_z_m + 0.55):\n'
 '                keep_cols.append(int(col))\n'
 '        gray_cols = np.asarray(keep_cols, dtype=int)\n'
 '\n'
 '    if gray_cols.size:\n'
 '        left_gray_y_span_m = float(y_axis[gray_cols.max()] - y_axis[gray_cols.min()])\n'
 '        left_gray_y_min_m = float(y_axis[gray_cols.min()])\n'
 '    else:\n'
 '        left_gray_y_span_m = 0.0\n'
 '        left_gray_y_min_m = np.nan\n'
 '\n'
 '    curve_z, _ = binary_extract_curve(binary_mask, cleaned, y_axis, z_axis)\n'
 '    active_cols = np.flatnonzero(np.isfinite(curve_z) & (y_axis <= LEFT_SUPPORT_Y_MAX_M))\n'
 '    if active_cols.size:\n'
 '        left_span_m = float(y_axis[active_cols.max()] - y_axis[active_cols.min()])\n'
 '        left_max_gap = binary_max_gap_m(active_cols, y_axis)\n'
 '        left_continuity = max(0.0, 1.0 - min(left_max_gap, 1.5) / 1.5) if '
 'np.isfinite(left_max_gap) else 0.0\n'
 '        detected_left_min = float(y_axis[active_cols.min()])\n'
 '    else:\n'
 '        left_span_m = 0.0\n'
 '        left_max_gap = float("inf")\n'
 '        left_continuity = 0.0\n'
 '        detected_left_min = np.nan\n'
 '\n'
 '    if np.isfinite(left_gray_y_min_m) and np.isfinite(detected_left_min):\n'
 '        left_edge_gap_m = max(0.0, detected_left_min - left_gray_y_min_m)\n'
 '    elif np.isfinite(left_gray_y_min_m):\n'
 '        left_edge_gap_m = left_gray_y_span_m\n'
 '    else:\n'
 '        left_edge_gap_m = 0.0\n'
 '    left_edge_score = max(0.0, 1.0 - min(left_edge_gap_m, LEFT_EDGE_SUPPORT_GAP_SCALE_M) / '
 'LEFT_EDGE_SUPPORT_GAP_SCALE_M)\n'
 '\n'
 '    if left_support_needed:\n'
 '        left_span_score = min(1.0, left_span_m / LEFT_SUPPORT_TARGET_SPAN_M)\n'
 '        left_support_score = (\n'
 '            0.42 * left_capture\n'
 '            + 0.25 * left_span_score\n'
 '            + 0.18 * left_continuity\n'
 '            + 0.15 * left_edge_score\n'
 '        )\n'
 '    else:\n'
 '        left_span_score = 1.0\n'
 '        left_support_score = 1.0\n'
 '\n'
 '    return {\n'
 '        "left_support_needed": int(left_support_needed),\n'
 '        "left_signal_fraction": float(left_signal_fraction),\n'
 '        "left_ice_energy_capture": float(left_capture),\n'
 '        "left_y_span_m": float(left_span_m),\n'
 '        "left_gray_y_span_m": float(left_gray_y_span_m),\n'
 '        "left_edge_gap_m": float(left_edge_gap_m),\n'
 '        "left_max_gap_m": float(left_max_gap),\n'
 '        "left_continuity_score": float(left_continuity),\n'
 '        "left_span_score": float(left_span_score),\n'
 '        "left_edge_score": float(left_edge_score),\n'
 '        "left_support_score": float(left_support_score),\n'
 '    }\n'
 '\n'
 '\n'
 'def binary_empty_left_rescue_meta(shape):\n'
 '    empty = np.zeros(shape, dtype=bool)\n'
 '    return {\n'
 '        "left_rescue_mask": empty,\n'
 '        "left_rescue_applied": 0,\n'
 '        "left_rescue_pixel_count": 0,\n'
 '        "left_rescue_threshold_high": np.nan,\n'
 '        "left_rescue_threshold_low": np.nan,\n'
 '        "left_support_before": np.nan,\n'
 '        "left_support_after": np.nan,\n'
 '        "left_edge_gap_before": np.nan,\n'
 '        "left_edge_gap_after": np.nan,\n'
 '    }\n'
 '\n'
 '\n'
 'def binary_apply_left_support_rescue(final_mask, cleaned, valid_mask, y_axis, z_axis, ice_z_m, '
 'config):\n'
 '    meta = binary_empty_left_rescue_meta(final_mask.shape)\n'
 '    before = binary_left_support_metrics(final_mask, cleaned, y_axis, z_axis, ice_z_m)\n'
 '    meta["left_support_before"] = before["left_support_score"]\n'
 '    meta["left_edge_gap_before"] = before["left_edge_gap_m"]\n'
 '    edge_gap_trigger = before["left_edge_gap_m"] >= LEFT_EDGE_EXTENSION_MIN_GAP_M\n'
 '    capture_trigger = before["left_ice_energy_capture"] < LEFT_RESCUE_CAPTURE_TRIGGER\n'
 '\n'
 '    if (not before["left_support_needed"]) or (before["left_support_score"] >= '
 'LEFT_RESCUE_MIN_SUPPORT_SCORE and not edge_gap_trigger and not capture_trigger):\n'
 '        meta["left_support_after"] = before["left_support_score"]\n'
 '        meta["left_edge_gap_after"] = before["left_edge_gap_m"]\n'
 '        return final_mask, meta\n'
 '\n'
 '    dy = float(np.nanmean(np.diff(y_axis)))\n'
 '    dz = float(np.nanmean(np.diff(z_axis)))\n'
 '    y_grid, z_grid = np.meshgrid(y_axis, z_axis)\n'
 '    left_down_m = min(float(config["window_down_m"]), LEFT_RESCUE_MAX_DOWN_M)\n'
 '    left_window = (\n'
 '        valid_mask\n'
 '        & np.isfinite(cleaned)\n'
 '        & (y_grid <= LEFT_SUPPORT_Y_MAX_M)\n'
 '        & (z_grid >= ice_z_m - left_down_m)\n'
 '        & (z_grid <= ice_z_m + config["window_up_m"])\n'
 '    )\n'
 '    left_values = cleaned[left_window]\n'
 '    if left_values.size < 20:\n'
 '        meta["left_support_after"] = before["left_support_score"]\n'
 '        meta["left_edge_gap_after"] = before["left_edge_gap_m"]\n'
 '        return final_mask, meta\n'
 '\n'
 '    local_high = float(np.nanpercentile(left_values, config["high_q"]))\n'
 '    local_low = float(np.nanpercentile(left_values, config["low_q"]))\n'
 '    local_low = min(local_low, local_high)\n'
 '    meta["left_rescue_threshold_high"] = local_high\n'
 '    meta["left_rescue_threshold_low"] = local_low\n'
 '\n'
 '    seed_mask = left_window & (cleaned >= local_high)\n'
 '    weak_mask = left_window & (cleaned >= local_low)\n'
 '    rescue_peak_threshold = local_low if (capture_trigger or edge_gap_trigger) else local_high\n'
 '    rescue_raw = binary_component_hysteresis(seed_mask, weak_mask)\n'
 '\n'
 '    ridge_mask = np.zeros_like(rescue_raw, dtype=bool)\n'
 '    half_width_px = meters_to_pixels(LEFT_RESCUE_RIDGE_HALF_WIDTH_M, dz, minimum=1)\n'
 '    left_cols = np.flatnonzero(np.any(left_window, axis=0))\n'
 '    for col in left_cols:\n'
 '        rows = np.flatnonzero(left_window[:, col] & np.isfinite(cleaned[:, col]))\n'
 '        if rows.size == 0:\n'
 '            continue\n'
 '        values = cleaned[rows, col]\n'
 '        if not np.any(np.isfinite(values)):\n'
 '            continue\n'
 '        peak_row = rows[int(np.nanargmax(values))]\n'
 '        if cleaned[peak_row, col] < rescue_peak_threshold:\n'
 '            continue\n'
 '        row0 = max(0, peak_row - half_width_px)\n'
 '        row1 = min(rescue_raw.shape[0], peak_row + half_width_px + 1)\n'
 '        ridge_mask[row0:row1, col] = True\n'
 '\n'
 '    ridge_seed = ridge_mask & weak_mask & (cleaned >= rescue_peak_threshold)\n'
 '    rescue_raw = binary_component_hysteresis(seed_mask | ridge_seed, weak_mask)\n'
 '    rescue_raw &= ridge_mask\n'
 '    close_y = meters_to_pixels(config["closing_y_m"], dy, minimum=1)\n'
 '    close_z = meters_to_pixels(config["closing_z_m"], dz, minimum=1)\n'
 '    if close_y > 0 and close_z > 0:\n'
 '        rescue_raw = binary_closing(rescue_raw, footprint=np.ones((close_z, close_y), '
 'dtype=bool))\n'
 '\n'
 '    min_pixels = max(1, int(round(0.5 * config["min_area_m2"] / max(abs(dy * dz), 1e-9))))\n'
 '    rescue_raw = remove_small_objects(rescue_raw, min_size=min_pixels, connectivity=2)\n'
 '\n'
 '    rescue_mask = np.zeros_like(rescue_raw, dtype=bool)\n'
 '    component_labels = label(rescue_raw, connectivity=2)\n'
 '    for region in regionprops(component_labels, intensity_image=np.nan_to_num(cleaned, '
 'nan=0.0)):\n'
 '        rows = region.coords[:, 0]\n'
 '        cols = region.coords[:, 1]\n'
 '        y_min = float(y_axis[int(cols.min())])\n'
 '        y_max = float(y_axis[int(cols.max())])\n'
 '        z_min = float(z_axis[int(rows.min())])\n'
 '        z_max = float(z_axis[int(rows.max())])\n'
 '        y_span = y_max - y_min\n'
 '        z_span = z_max - z_min\n'
 '        y_centroid = float(y_axis[int(round(region.centroid[1]))])\n'
 '        z_centroid = float(z_axis[int(round(region.centroid[0]))])\n'
 '        area_m2 = float(region.area * abs(dy) * abs(dz))\n'
 '\n'
 '        enough_support = (y_span >= LEFT_RESCUE_MIN_Y_SPAN_M) or (area_m2 >= 0.5 * '
 'config["min_area_m2"])\n'
 '        near_ice = (z_max >= ice_z_m - left_down_m) and (z_min <= ice_z_m + '
 'config["window_up_m"])\n'
 '        center_line_like = (abs(y_centroid) <= 0.35) and (y_span <= 0.50) and (z_span >= 1.20) '
 'and (z_centroid < ice_z_m - 0.20)\n'
 '        lower_lobe_like = (z_centroid < ice_z_m - left_down_m) or ((z_centroid < ice_z_m - 0.95) '
 'and (y_span <= 4.50))\n'
 '\n'
 '        if enough_support and near_ice and not center_line_like and not lower_lobe_like:\n'
 '            rescue_mask[rows, cols] = True\n'
 '\n'
 '    rescue_mask &= left_window\n'
 '    rescue_mask &= ~final_mask\n'
 '    if not np.any(rescue_mask):\n'
 '        meta["left_support_after"] = before["left_support_score"]\n'
 '        meta["left_edge_gap_after"] = before["left_edge_gap_m"]\n'
 '        return final_mask, meta\n'
 '\n'
 '    merged = final_mask | rescue_mask\n'
 '    after = binary_left_support_metrics(merged, cleaned, y_axis, z_axis, ice_z_m)\n'
 '    meta["left_support_after"] = after["left_support_score"]\n'
 '    meta["left_edge_gap_after"] = after["left_edge_gap_m"]\n'
 '    improved_score = after["left_support_score"] > before["left_support_score"] + 0.02\n'
 '    improved_edge = before["left_edge_gap_m"] - after["left_edge_gap_m"] > 0.25\n'
 '    if not (improved_score or improved_edge):\n'
 '        return final_mask, meta\n'
 '\n'
 '    meta["left_rescue_mask"] = rescue_mask\n'
 '    meta["left_rescue_applied"] = 1\n'
 '    meta["left_rescue_pixel_count"] = int(np.count_nonzero(rescue_mask))\n'
 '    return merged, meta\n'
 '\n'
 '\n'
 'def binary_segment_ice(cleaned, valid_mask, y_axis, z_axis, ice_z_m, config):\n'
 '    dy = float(np.nanmean(np.diff(y_axis)))\n'
 '    dz = float(np.nanmean(np.diff(z_axis)))\n'
 '    y_grid, z_grid = np.meshgrid(y_axis, z_axis)\n'
 '    cleaned = np.asarray(cleaned, dtype=float).copy()\n'
 '    cleaned[~valid_mask] = np.nan\n'
 '\n'
 '    window_mask = (\n'
 '        valid_mask\n'
 '        & np.isfinite(cleaned)\n'
 '        & (z_grid >= ice_z_m - config["window_down_m"])\n'
 '        & (z_grid <= ice_z_m + config["window_up_m"])\n'
 '    )\n'
 '    values = cleaned[window_mask]\n'
 '    if values.size < 10:\n'
 '        empty = np.zeros_like(valid_mask, dtype=bool)\n'
 '        meta = {\n'
 '            "raw_mask": empty,\n'
 '            "seed_mask": empty,\n'
 '            "weak_mask": empty,\n'
 '            "removed_mask": empty,\n'
 '            "threshold_high": np.nan,\n'
 '            "threshold_low": np.nan,\n'
 '        }\n'
 '        meta.update(binary_empty_left_rescue_meta(valid_mask.shape))\n'
 '        return empty, meta\n'
 '\n'
 '    threshold_high = float(np.nanpercentile(values, config["high_q"]))\n'
 '    threshold_low = float(np.nanpercentile(values, config["low_q"]))\n'
 '    threshold_low = min(threshold_low, threshold_high)\n'
 '\n'
 '    seed_mask = window_mask & (cleaned >= threshold_high)\n'
 '    weak_mask = window_mask & (cleaned >= threshold_low)\n'
 '    raw_mask = binary_component_hysteresis(seed_mask, weak_mask)\n'
 '\n'
 '    close_y = meters_to_pixels(config["closing_y_m"], dy, minimum=1)\n'
 '    close_z = meters_to_pixels(config["closing_z_m"], dz, minimum=1)\n'
 '    if close_y > 0 and close_z > 0:\n'
 '        raw_mask = binary_closing(raw_mask, footprint=np.ones((close_z, close_y), dtype=bool))\n'
 '\n'
 '    open_y = meters_to_pixels(config["opening_y_m"], dy, minimum=1)\n'
 '    open_z = meters_to_pixels(config["opening_z_m"], dz, minimum=1)\n'
 '    if open_y > 0 and open_z > 0:\n'
 '        raw_mask = binary_opening(raw_mask, footprint=np.ones((open_z, open_y), dtype=bool))\n'
 '\n'
 '    min_pixels = max(1, int(round(config["min_area_m2"] / max(abs(dy * dz), 1e-9))))\n'
 '    raw_mask = remove_small_objects(raw_mask, min_size=min_pixels, connectivity=2)\n'
 '    hole_pixels = max(1, int(round(config["hole_area_m2"] / max(abs(dy * dz), 1e-9))))\n'
 '    raw_mask = remove_small_holes(raw_mask, area_threshold=hole_pixels, connectivity=2)\n'
 '    raw_mask &= valid_mask\n'
 '\n'
 '    component_labels = label(raw_mask, connectivity=2)\n'
 '    final_mask = np.zeros_like(raw_mask, dtype=bool)\n'
 '    removed_mask = np.zeros_like(raw_mask, dtype=bool)\n'
 '    for region in regionprops(component_labels, intensity_image=np.nan_to_num(cleaned, '
 'nan=0.0)):\n'
 '        rows = region.coords[:, 0]\n'
 '        cols = region.coords[:, 1]\n'
 '        y_min = float(y_axis[int(cols.min())])\n'
 '        y_max = float(y_axis[int(cols.max())])\n'
 '        z_min = float(z_axis[int(rows.min())])\n'
 '        z_max = float(z_axis[int(rows.max())])\n'
 '        y_span = y_max - y_min\n'
 '        z_span = z_max - z_min\n'
 '        y_centroid = float(y_axis[int(round(region.centroid[1]))])\n'
 '        z_centroid = float(z_axis[int(round(region.centroid[0]))])\n'
 '        area_m2 = float(region.area * abs(dy) * abs(dz))\n'
 '\n'
 '        near_ice = (z_max >= ice_z_m - config["window_down_m"]) and (z_min <= ice_z_m + '
 'config["window_up_m"])\n'
 '        enough_support = (y_span >= config["min_y_span_m"]) or (area_m2 >= '
 'config["min_area_m2"])\n'
 '        center_line_like = (abs(y_centroid) <= 0.35) and (y_span <= 0.50) and (z_span >= 1.20) '
 'and (z_centroid < ice_z_m - 0.20)\n'
 '        lower_lobe_like = (z_centroid < ice_z_m - 0.95) and (y_span <= 4.50)\n'
 '\n'
 '        if near_ice and enough_support and not center_line_like and not lower_lobe_like:\n'
 '            final_mask[rows, cols] = True\n'
 '        else:\n'
 '            removed_mask[rows, cols] = True\n'
 '\n'
 '    final_mask &= window_mask\n'
 '    final_mask, left_rescue_meta = binary_apply_left_support_rescue(final_mask, cleaned, '
 'valid_mask, y_axis, z_axis, ice_z_m, config)\n'
 '    final_mask &= window_mask\n'
 '    return final_mask, {\n'
 '        "raw_mask": raw_mask,\n'
 '        "seed_mask": seed_mask,\n'
 '        "weak_mask": weak_mask,\n'
 '        "removed_mask": removed_mask,\n'
 '        "threshold_high": threshold_high,\n'
 '        "threshold_low": threshold_low,\n'
 '        **left_rescue_meta,\n'
 '    }\n'
 '\n'
 '\n'
 'def binary_score_mask(binary_mask, cleaned, context, y_axis, z_axis, ice_z_m):\n'
 '    dy = float(np.nanmean(np.diff(y_axis)))\n'
 '    y_grid, z_grid = np.meshgrid(y_axis, z_axis)\n'
 '    finite_clean = np.isfinite(cleaned)\n'
 '    ice_window = finite_clean & (z_grid >= ice_z_m - 0.85) & (z_grid <= ice_z_m + 0.55)\n'
 '    broader_ice_window = finite_clean & (z_grid >= ice_z_m - 1.25) & (z_grid <= ice_z_m + 0.75)\n'
 '    center_nonice = binary_mask & (np.abs(y_grid) <= 0.30) & (z_grid < ice_z_m - 0.50)\n'
 '    lower_lobe = binary_mask & (z_grid < ice_z_m - 1.10) & (np.abs(y_grid) <= 7.5)\n'
 '\n'
 '    ice_energy_total = safe_energy(cleaned, ice_window)\n'
 '    broader_energy_total = safe_energy(cleaned, broader_ice_window)\n'
 '    ice_energy_in_mask = safe_energy(cleaned, binary_mask & ice_window)\n'
 '    broader_energy_in_mask = safe_energy(cleaned, binary_mask & broader_ice_window)\n'
 '    mask_energy = safe_energy(cleaned, binary_mask)\n'
 '    mask_pixels = int(np.count_nonzero(binary_mask))\n'
 '\n'
 '    ice_energy_capture = ice_energy_in_mask / ice_energy_total if ice_energy_total else 0.0\n'
 '    broader_capture = broader_energy_in_mask / broader_energy_total if broader_energy_total else '
 '0.0\n'
 '    center_residual = safe_energy(cleaned, center_nonice) / mask_energy if mask_energy else 0.0\n'
 '    lobe_residual = safe_energy(cleaned, lower_lobe) / mask_energy if mask_energy else 0.0\n'
 '    left_metrics = binary_left_support_metrics(binary_mask, cleaned, y_axis, z_axis, ice_z_m)\n'
 '\n'
 '    curve_z, curve_weight = binary_extract_curve(binary_mask, cleaned, y_axis, z_axis)\n'
 '    curve_z_reconstructed, curve_interpolated_mask = binary_interpolate_short_gaps(curve_z, '
 'y_axis)\n'
 '    curve_weight_reconstructed = binary_curve_weight_with_interpolation(\n'
 '        curve_weight,\n'
 '        curve_z,\n'
 '        curve_interpolated_mask,\n'
 '    )\n'
 '    active_cols = np.flatnonzero(np.isfinite(curve_z))\n'
 '    if active_cols.size:\n'
 '        y_span = float(y_axis[active_cols.max()] - y_axis[active_cols.min()])\n'
 '        max_gap = binary_max_gap_m(active_cols, y_axis)\n'
 '        smooth_curve = binary_smooth_curve(curve_z, y_axis, sigma_cols=max(1.0, 0.20 / '
 'abs(dy)))\n'
 '        curve_residual = curve_z - smooth_curve\n'
 '        curve_roughness_m = '
 'float(np.nanmedian(np.abs(curve_residual[np.isfinite(curve_residual)]))) if '
 'np.any(np.isfinite(curve_residual)) else 0.0\n'
 '        z_alignment_m = float(abs(np.nanmedian(curve_z[active_cols]) - ice_z_m))\n'
 '    else:\n'
 '        y_span = 0.0\n'
 '        max_gap = float("inf")\n'
 '        curve_roughness_m = 9.0\n'
 '        z_alignment_m = 9.0\n'
 '\n'
 '    y_span_score = min(1.0, y_span / 8.0)\n'
 '    continuity_score = max(0.0, 1.0 - min(max_gap, 2.0) / 2.0) if np.isfinite(max_gap) else 0.0\n'
 '    roughness_score = max(0.0, 1.0 - curve_roughness_m / 0.35)\n'
 '    alignment_score = max(0.0, 1.0 - z_alignment_m / 0.85)\n'
 '    area_fraction = mask_pixels / max(1, int(np.count_nonzero(finite_clean)))\n'
 '\n'
 '    score = (\n'
 '        0.30 * ice_energy_capture\n'
 '        + 0.16 * broader_capture\n'
 '        + 0.13 * y_span_score\n'
 '        + 0.10 * continuity_score\n'
 '        + 0.10 * alignment_score\n'
 '        + 0.05 * roughness_score\n'
 '        + 0.12 * left_metrics["left_support_score"]\n'
 '        - 0.18 * center_residual\n'
 '        - 0.20 * lobe_residual\n'
 '        - 0.06 * abs(area_fraction - 0.035) / 0.035\n'
 '    )\n'
 '    if ice_energy_capture < 0.45:\n'
 '        score -= 0.35 * (0.45 - ice_energy_capture)\n'
 '    if y_span < 2.0:\n'
 '        score -= 0.10 * (2.0 - y_span)\n'
 '    if left_metrics["left_support_needed"] and left_metrics["left_support_score"] < 0.45:\n'
 '        score -= 0.16 * (0.45 - left_metrics["left_support_score"])\n'
 '\n'
 '    return {\n'
 '        "binary_score": float(score),\n'
 '        "ice_energy_capture": float(ice_energy_capture),\n'
 '        "broader_ice_capture": float(broader_capture),\n'
 '        "binary_center_residual": float(center_residual),\n'
 '        "binary_lobe_residual": float(lobe_residual),\n'
 '        "y_span_m": float(y_span),\n'
 '        "max_gap_m": float(max_gap),\n'
 '        "continuity_score": float(continuity_score),\n'
 '        "curve_roughness_m": float(curve_roughness_m),\n'
 '        "z_alignment_m": float(z_alignment_m),\n'
 '        "area_fraction": float(area_fraction),\n'
 '        "mask_pixels": int(mask_pixels),\n'
 '        "curve_z": curve_z,\n'
 '        "curve_weight": curve_weight,\n'
 '        "curve_z_reconstructed": curve_z_reconstructed,\n'
 '        "curve_weight_reconstructed": curve_weight_reconstructed,\n'
 '        "curve_interpolated_mask": curve_interpolated_mask,\n'
 '        "curve_interpolated_point_count": int(np.count_nonzero(curve_interpolated_mask)),\n'
 '        "curve_interpolated_span_m": float(np.count_nonzero(curve_interpolated_mask) * '
 'abs(dy)),\n'
 '        **left_metrics,\n'
 '    }\n'
 '\n'
 '\n'
 'def binary_render_figure(ping_idx, cleaned, binary_mask, binary_meta, metrics, config, y_axis, '
 'z_axis, output_path):\n'
 '    extent = [float(y_axis[0]), float(y_axis[-1]), float(z_axis[0]), float(z_axis[-1])]\n'
 '    mvp_cmap = CMAP.copy()\n'
 '    mvp_cmap.set_bad("#000000")\n'
 '    overlay = np.ma.masked_where(~binary_mask, binary_mask.astype(float))\n'
 '    raw_overlay = np.ma.masked_where(~binary_meta["raw_mask"], '
 'binary_meta["raw_mask"].astype(float))\n'
 '    removed_overlay = np.ma.masked_where(~binary_meta["removed_mask"], '
 'binary_meta["removed_mask"].astype(float))\n'
 '    left_rescue_mask = np.asarray(binary_meta.get("left_rescue_mask", np.zeros_like(binary_mask, '
 'dtype=bool)), dtype=bool)\n'
 '    rescue_overlay = np.ma.masked_where(~left_rescue_mask, left_rescue_mask.astype(float))\n'
 '\n'
 '    fig, axes = plt.subplots(2, 2, figsize=(13.0, 8.2), dpi=150, constrained_layout=True)\n'
 '    axes[0, 0].imshow(cleaned, extent=extent, origin="lower", aspect="equal", cmap=mvp_cmap, '
 'vmin=0.0, vmax=1.0)\n'
 '    axes[0, 0].set_title("Gray denoised input", fontname="Arial")\n'
 '\n'
 '    final_curve = metrics.get("curve_z_reconstructed", metrics["curve_z"])\n'
 '    interpolated_mask = np.asarray(metrics.get("curve_interpolated_mask", '
 'np.zeros_like(final_curve, dtype=bool)), dtype=bool)\n'
 '\n'
 '    axes[0, 1].imshow(cleaned, extent=extent, origin="lower", aspect="equal", cmap=mvp_cmap, '
 'vmin=0.0, vmax=1.0)\n'
 '    axes[0, 1].imshow(overlay, extent=extent, origin="lower", aspect="equal", cmap="winter", '
 'alpha=0.60, vmin=0, vmax=1)\n'
 '    plot_indexed_segments(axes[0, 1], y_axis, metrics["curve_z"], metrics["curve_z"], y_axis, '
 'color="#ff4d4d", linewidth=0.8, alpha=0.55, label="measured")\n'
 '    plot_indexed_segments(axes[0, 1], y_axis, final_curve, final_curve, y_axis, color="#00d5ff", '
 'linewidth=1.3, label="short-gap connected")\n'
 '    if np.any(interpolated_mask):\n'
 '        axes[0, 1].scatter(y_axis[interpolated_mask], final_curve[interpolated_mask], s=8, '
 'color="#00d5ff", alpha=0.85, linewidths=0)\n'
 '    axes[0, 1].legend(loc="lower right", fontsize=7, frameon=True)\n'
 '    axes[0, 1].set_title(f"Selected binary ice mask | {config[\'name\']}", fontname="Arial")\n'
 '\n'
 '    axes[1, 0].imshow(cleaned, extent=extent, origin="lower", aspect="equal", cmap=mvp_cmap, '
 'vmin=0.0, vmax=1.0)\n'
 '    axes[1, 0].imshow(raw_overlay, extent=extent, origin="lower", aspect="equal", cmap="Greens", '
 'alpha=0.50, vmin=0, vmax=1)\n'
 '    axes[1, 0].imshow(removed_overlay, extent=extent, origin="lower", aspect="equal", '
 'cmap="Reds", alpha=0.50, vmin=0, vmax=1)\n'
 '    if np.any(left_rescue_mask):\n'
 '        axes[1, 0].imshow(rescue_overlay, extent=extent, origin="lower", aspect="equal", '
 'cmap="cool", alpha=0.60, vmin=0, vmax=1)\n'
 '    axes[1, 0].set_title("Raw mask + removed components + left rescue", fontname="Arial")\n'
 '\n'
 '    axp = axes[1, 1]\n'
 '    smooth_curve = binary_smooth_curve(final_curve, y_axis, sigma_cols=max(1.0, 0.20 / '
 'abs(np.nanmean(np.diff(y_axis)))))\n'
 '    plot_indexed_segments(axp, y_axis, metrics["curve_z"], metrics["curve_z"], y_axis, '
 'color="#c44e52", linewidth=1.1, alpha=0.55, label="measured center")\n'
 '    plot_indexed_segments(axp, y_axis, final_curve, final_curve, y_axis, color="#00a8cc", '
 'linewidth=1.4, label="short-gap connected")\n'
 '    plot_indexed_segments(axp, y_axis, smooth_curve, final_curve, y_axis, color="#4c72b0", '
 'linewidth=1.5, label="gap-aware smoothed")\n'
 '    axp.axhline(metrics["ice_z_m"], color="#c98200", linestyle="--", linewidth=1.2, '
 'label="gray-stage ice z")\n'
 '    axp.set_xlim(float(y_axis[0]), float(y_axis[-1]))\n'
 '    axp.set_ylim(float(z_axis[0]), float(z_axis[-1]))\n'
 '    axp.set_xlabel("y_s port / cross-track (m)", fontname="Arial")\n'
 '    axp.set_ylabel("z_s center-beam forward (m)", fontname="Arial")\n'
 '    axp.set_title("Extracted ice-band curve", fontname="Arial")\n'
 '    axp.grid(True, alpha=0.25, linestyle=":")\n'
 '    axp.legend(loc="lower right", fontsize=7, frameon=True)\n'
 '\n'
 '    for ax in axes.ravel()[:3]:\n'
 '        ax.set_xlabel("y_s port / cross-track (m)", fontname="Arial")\n'
 '        ax.set_ylabel("z_s center-beam forward (m)", fontname="Arial")\n'
 '        ax.grid(True, alpha=0.25, linestyle=":")\n'
 '\n'
 '    fig.suptitle(\n'
 '        f"Binary ice-mask auto-score | ping {ping_idx} | score={metrics[\'binary_score\']:.3f} | '
 "left={metrics['left_support_score']:.3f} | interp={metrics.get('curve_interpolated_point_count', "
 '0)}",\n'
 '        y=1.02,\n'
 '        fontname="Arial",\n'
 '    )\n'
 '    fig.savefig(output_path, dpi=180, bbox_inches="tight")\n'
 '    plt.close(fig)\n',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

def get_cell_source(cell_index: int) -> str:
    """Return one retained implementation block by its stable index."""
    if cell_index < 0 or cell_index >= len(CELL_SOURCES):
        raise IndexError(f"Algorithm block index out of range: {cell_index}")
    return CELL_SOURCES[cell_index]
